// GENERATED by scripts/check-tile-images.mjs on each build. Do not edit.
// Tile images present in public/ at build time.
export const AVAILABLE_TILES: ReadonlySet<string> = new Set([
  "/images/vibes/garden-party.jpg",
  "/images/vibes/timeless-estate.jpg",
  "/images/vibes/european-summer.jpg",
  "/images/vibes/moody-romance.jpg",
  "/images/vibes/colorful-celebration.jpg",
  "/images/vibes/something-blue.jpg",
  "/images/vibes/elevated-western.jpg",
  "/images/vibes/editorial-romance.jpg",
  "/images/arch/feyre-arch.jpg",
  "/images/arch/elaine-arch.jpg",
  "/images/arch/cassian-arch.jpg",
  "/images/arch/gwen-arch.jpg",
  "/images/arch/wooden-cross.jpg",
  "/images/arch/wooden-arch.jpg",
  "/images/metal/gold.jpg",
  "/images/metal/silver.jpg"
]);
