// GENERATED by scripts/check-tile-images.mjs on each build. Do not edit.
// Tile images present in public/ at build time.
export const AVAILABLE_TILES: ReadonlySet<string> = new Set([
  "/images/vibes/garden-party.jpg",
  "/images/vibes/timeless-estate.jpg",
  "/images/vibes/european-summer.jpg",
  "/images/vibes/moody-romance.jpg",
  "/images/vibes/colorful-celebration.jpg",
  "/images/vibes/something-blue.jpg",
  "/images/vibes/elevated-western.jpg",
  "/images/vibes/editorial-romance.jpg"
]);
